Add default methods to Operand to get the shape and datatype from asOutput().
tensorflow/java pull request #151
Opened 2020-11-16 04:47 UTC by rnett

Add default methods to Operand to get the shape and datatype from `asOutput()`.

Fixes #146.

2020-11-16 21:52 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/Operand.java
> +  default Shape shape(){
I guess we want to mark the same methods in [`Output`](https://github.com/tensorflow/java/blob/91400f4e0f26f4324a8843599810baf346583395/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/Output.java#L40) as `@Override` now

2020-11-16 21:53 UTC, karllessard requested changes
Thanks for the PR @rnett, just a small change and then we are good

2020-11-19 02:42 UTC, karllessard commented
@rnett , I've started to create PRs for the type-system refactoring (see #139) and the first one (#153) partially covers the changes in your PR, but wrt the new design. Plus, the addition of `dataType()` in `Operand` will come soon after, again with some alterations.

Therefore, I would like to see if you would agree to close your PR to avoid any conflict.

2020-11-19 03:01 UTC, rnett commented
I saw that, it's fine by me.

2020-11-19 03:01 UTC, closed without merging