Add option to run TensorFlow job on the preferred device (via Scope)
tensorflow/java pull request #159
Opened 2020-11-27 13:30 UTC by zaleslaw

Related to the issue #77

2020-11-28 22:12 UTC, karllessard requested changes

2020-11-28 22:12 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/gen/annotations/org/tensorflow/op/Ops.java
> +import org.tensorflow.*;
Let's avoid wildcard imports, as per [Google Java style guide](https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports) suggestion.

2020-11-28 22:12 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/op/math/Abs.java
> +    opBuilder.setDevice(scope.makeDeviceString());
All generated ops should have been update by your change in the op generator above, they should be all updated by this PR as well, not only this one (there must be 1000+ files to be added).

2020-11-28 22:12 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/op/Scope.java
> +  // TODO: add docs
TODO: add docs :)

2020-11-28 22:12 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/test/java/org/tensorflow/op/core/ConstantTest.java
> +import org.tensorflow.*;
No wildcard imports

2020-11-28 22:12 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/test/java/org/tensorflow/op/core/ConstantTest.java
> +      //DeviceSpec deviceSpec = DeviceSpec.newBuilder().build();
This comment is probably a leftover

2020-11-28 22:12 UTC, karllessard commented on tensorflow-core/tensorflow-core-generator/src/main/java/org/tensorflow/processor/operator/OperatorProcessor.java
> +
The `Ops` class should now have this new method in it but it does not appear in the version you've committed.

Also, I would rephrase its documentation for something like this:

"Returns an API that places the created operations on the device(s) matching the provided spec. @see..."

2020-11-29 05:52 UTC, zaleslaw commented
Thank you, it was a draft PR with code changes, but without code
generation, I will update the PR and notify you

вс, 29 нояб. 2020 г., 1:13 Karl Lessard <notifications@github.com>:

> *@karllessard* requested changes on this pull request.
> ------------------------------
>
> In
> tensorflow-core/tensorflow-core-api/src/gen/annotations/org/tensorflow/op/Ops.java
> <https://github.com/tensorflow/java/pull/159#discussion_r532111315>:
>
> > @@ -19,11 +19,8 @@
>
>  import java.nio.charset.Charset;
>  import java.util.List;
> -import org.tensorflow.DataType;
> -import org.tensorflow.EagerSession;
> -import org.tensorflow.ExecutionEnvironment;
> -import org.tensorflow.Operand;
> -import org.tensorflow.Tensor;
> +
> +import org.tensorflow.*;
>
> Let's avoid wildcard imports, as per Google Java style guide
> <https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports>
> suggestion.
> ------------------------------
>
> In
> tensorflow-core/tensorflow-core-api/src/gen/java/org/tensorflow/op/math/Abs.java
> <https://github.com/tensorflow/java/pull/159#discussion_r532111490>:
>
> > @@ -50,6 +50,7 @@
>    @Endpoint(describeByClass = true)
>    public static <T extends TNumber> Abs<T> create(Scope scope, Operand<T> x) {
>      OperationBuilder opBuilder = scope.env().opBuilder("Abs", scope.makeOpName("Abs"));
> +    opBuilder.setDevice(scope.makeDeviceString());
>
> All generated ops should have been update by your change in the op
> generator above, they should be all updated by this PR as well, not only
> this one (there must be 1000+ files to be added).
> ------------------------------
>
> In
> tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/op/Scope.java
> <https://github.com/tensorflow/java/pull/159#discussion_r532111818>:
>
> > @@ -121,7 +123,12 @@ public Scope withSubScope(String childScopeName) {
>     * @throws IllegalArgumentException if the name is invalid
>     */
>    public Scope withName(String opName) {
> -    return new Scope(env, nameScope.withName(opName), controlDependencies);
> +    return new Scope(env, nameScope.withName(opName), controlDependencies, deviceSpec);
> +  }
> +
> +  // TODO: add docs
>
> TODO: add docs :)
> ------------------------------
>
> In
> tensorflow-core/tensorflow-core-api/src/test/java/org/tensorflow/op/core/ConstantTest.java
> <https://github.com/tensorflow/java/pull/159#discussion_r532111885>:
>
> >  import org.junit.jupiter.api.Test;
> -import org.tensorflow.AutoCloseableList;
> -import org.tensorflow.Graph;
> -import org.tensorflow.Session;
> -import org.tensorflow.Tensor;
> +import org.tensorflow.*;
>
> No wildcard imports
> ------------------------------
>
> In
> tensorflow-core/tensorflow-core-api/src/test/java/org/tensorflow/op/core/ConstantTest.java
> <https://github.com/tensorflow/java/pull/159#discussion_r532111926>:
>
> > +
> +      Output<TInt32> aOps = g
> +              .opBuilder("Const", "aOps")
> +              .setAttr("dtype", a.dataType())
> +              .setAttr("value", a)
> +              .setDevice("/job:localhost/replica:0/task:0/device:CPU:0")
> +              .build()
> +              .output(0);
> +      DeviceSpec deviceSpec = DeviceSpec.newBuilder()
> +              .job("localhost")
> +              .replica(0)
> +              .task(1)
> +              .deviceType(DeviceSpec.DeviceType.CPU)
> +              .build();
> +
> +      //DeviceSpec deviceSpec = DeviceSpec.newBuilder().build();
>
> This comment is probably a leftover
> ------------------------------
>
> In
> tensorflow-core/tensorflow-core-generator/src/main/java/org/tensorflow/processor/operator/OperatorProcessor.java
> <https://github.com/tensorflow/java/pull/159#discussion_r532112345>:
>
> > @@ -537,6 +538,18 @@ private static TypeSpec buildTopClass(OpsSpec spec) {
>                  T_SCOPE)
>              .build());
>
> +    opsBuilder.addMethod(
> +            MethodSpec.methodBuilder("withDevice")
> +                    .addModifiers(Modifier.PUBLIC)
> +                    .addParameter(T_DEVICE_SPEC, "deviceSpec")
> +                    .returns(T_OPS)
> +                    .addStatement("return new Ops(scope.withDevice(deviceSpec))")
> +                    .addJavadoc(
> +                            "Returns an API that uses the provided DeviceSpec for an op.\n\n"
> +                                    + "@see {@link $T#withDevice(DeviceSpec)}\n",
> +                            T_SCOPE)
> +                    .build());
> +
>
> The Ops class should now have this new method in it but it does not
> appear in the version you've committed.
>
> Also, I would rephrase its documentation for something like this:
>
> "Returns an API that places the created operations on the device(s)
> matching the provided spec. @see <https://github.com/see>..."
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/java/pull/159#pullrequestreview-540420086>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJEUHLO5NBCOROTOWXJVXTSSFYW3ANCNFSM4UE5ICSQ>
> .
>

2020-11-29 14:35 UTC, karllessard commented
Ah, did you marked it as a draft when you've created your PR? My GitHub iPad app did not tell me this, maybe a missing feature in the app. But yes, I think with only these small changes, your PR will be ready to be merged, thanks!

2020-11-29 14:58 UTC, zaleslaw commented
No, I didn't mark, sorry for that, but your comments are useful, because
now it's clear what should be checked for successful PR

вс, 29 нояб. 2020 г., 17:35 Karl Lessard <notifications@github.com>:

> Ah, did you marked it as a draft when you've created your PR? My GitHub
> iPad app did not tell me this, maybe a missing feature in the app. But yes,
> I think with only these small changes, your PR will be ready to be merged,
> thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/java/pull/159#issuecomment-735404180>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJEUHNFSXENZ6SKG5DIDVLSSJL2RANCNFSM4UE5ICSQ>
> .
>

2020-11-30 11:45 UTC, zaleslaw commented
@karllessard I've updated the PR and fixed all your proposals, please have a look

2020-11-30 14:18 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/bazel/op_generator/op_generator.cc
> +
Hey @zaleslaw , I have another change to propose you that I just thought of. I think if we merge together `scope.applyControlDependencies` and this new step for adding the device string to the `opBuilder` would make the whole process of building an op simpler, especially with non-generated ones.

So what about that:
1. We rename `scope.applyControlDependencies(opBuilder)` to `scope.apply(opBuilder)`
2. In `Scope.apply`, we apply both control dependencies, the device string (and eventually more data if needed)

By doing so, we also won't need `scope.makeDeviceString()` anymore. Let me know what you think

2020-11-30 14:34 UTC, zaleslaw commented
Need a time to think about it



пн, 30 нояб. 2020 г. в 17:19, Karl Lessard <notifications@github.com>:

> *@karllessard* commented on this pull request.
> ------------------------------
>
> In
> tensorflow-core/tensorflow-core-api/src/bazel/op_generator/op_generator.cc
> <https://github.com/tensorflow/java/pull/159#discussion_r532629551>:
>
> > @@ -246,6 +246,10 @@ void RenderFactoryMethods(const OpSpec& op, const Type& op_class,
>        writer->EndLine();
>      }
>    }
> +  // Add Device String
> +  writer->Append("opBuilder.setDevice(scope.makeDeviceString());");
> +  writer->EndLine();
> +
>
> Hey @zaleslaw <https://github.com/zaleslaw> , I have another change to
> propose you that I just thought of. I think if we merge together
> scope.applyControlDependencies and this new step for adding the device
> string to the opBuilder would make the whole process of building an op
> simpler, especially with non-generated ones.
>
> So what about that:
>
>    1. We rename scope.applyControlDependencies(opBuilder) to
>    scope.apply(opBuilder)
>    2. In Scope.apply, we apply both control dependencies, the device
>    string (and eventually more data if needed)
>
> By doing so, we also won't need scope.makeDeviceString() anymore. Let me
> know what you think
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tensorflow/java/pull/159#pullrequestreview-540949585>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJEUHNB3AY7GGXNB2HE65DSSOSVRANCNFSM4UE5ICSQ>
> .
>

2020-12-03 15:05 UTC, zaleslaw commented
@karllessard I've updated a PR according your refactoring idea, but I have some troubles with quick build
"Failed to execute goal on project tensorflow-core-api: Could not resolve dependencies for project org.tensorflow:tensorflow-core-api:jar:0.3.0-SNAPSHOT: Could not find artifact org.tensorflow:tensorflow-core-api:jar:linux-x86_64:0.3.0-SNAPSHOT in ossrh-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project tensorflow-core-api: Could not resolve dependencies for project org.tensorflow:tensorflow-core-api:jar:0.3.0-SNAPSHOT: Could not find artifact org.tensorflow:tensorflow-core-api:jar:linux-x86_64:0.3.0-SNAPSHOT in ossrh-snapshots (https://oss.sonatype.org/content/repositories/snapshots)"

Could you pleas help with this issue?

2020-12-03 22:06 UTC, karllessard commented
@zaleslaw since your PR changes the generated files, we shouldn't use quick build anyway, I'll force a full build and see how it goes (independently to this, I suspect the missing artifact is due again to our trouble building all native artifacts on GitHub actions...)

2020-12-03 22:08 UTC, karllessard approved these changes

2020-12-04 04:26 UTC, merged

2020-12-04 04:29 UTC, karllessard commented
Full build passed (well partially, GPU-MKL timed out again on Linux and it's unrelated), thanks @zaleslaw !

2020-12-04 08:12 UTC, zaleslaw commented
Happy to hear!

2020-12-06 05:02 UTC, aday00 commented
Thanks @zaleslaw and @karllessard!!