Nicer error messages for mode-forbidden ops
tensorflow/java pull request #169
Opened 2020-12-09 22:55 UTC by rnett

Adds a way to forbid ops in `ExecutionEnviroment`s, uses it to forbid Placeholder, Variable, and Assign in eager mode.  As far as I know there's no way to detect ahead of time whether an op is forbidden, so this list will have to be added to as people run into mode-specific ops.  These three are likely to be the most common though.

2021-01-01 15:41 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/EagerOperationBuilder.java
> +      throw new IllegalArgumentException("Op " + type + " is not valid in eager mode.");
can you please add a space after `if` and also wrap the `throw` statement in a block `{...}`? This is more in line with the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used) that we follow in this project.

2021-01-01 15:42 UTC, karllessard requested changes

2021-01-01 15:42 UTC, karllessard commented on tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/GraphOperationBuilder.java
> +
same comment as [here](https://github.com/tensorflow/java/pull/169/files#r550779534)

2021-01-01 15:45 UTC, karllessard commented
What about moving the `isOpEnabled` check [here](https://github.com/tensorflow/java/blob/f85623ed366d903cfddb75177725dc276f359b15/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/Graph.java#L149) and [here](https://github.com/tensorflow/java/blob/f85623ed366d903cfddb75177725dc276f359b15/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/EagerSession.java#L274) to avoid instantiating an operation builder if the op is not supported?

2021-01-01 23:48 UTC, rnett commented
> What about moving the `isOpEnabled` check [here](https://github.com/tensorflow/java/blob/f85623ed366d903cfddb75177725dc276f359b15/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/Graph.java#L149) and [here](https://github.com/tensorflow/java/blob/f85623ed366d903cfddb75177725dc276f359b15/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/EagerSession.java#L274) to avoid instantiating an operation builder if the op is not supported?

There's a few places in tests, but that seems fine since it's package private.

2021-01-02 15:21 UTC, karllessard approved these changes

2021-01-02 15:22 UTC, merged